blank_issues_enabled: false
contact_links:
  - name: \U0001F4AC Discussion
    url: https://github.com/arturomoncadatorres/lego-mindstorms/discussions
    about: If you have any questions, comments, or feedback, open a discussion.
    context:
        button-text: Go to discussions
